<?php

namespace FilterEverything\Filter;

if ( ! defined('ABSPATH') ) {
    exit;
}

/**
 * Class autoloader for the plugin.
 *
 * Two lookup strategies, in this order:
 *
 *  1. Class maps (generated by bin/build-classmap.php into src/classmap.php
 *     and pro/classmap.php). Needed because the historical classes all live in
 *     the flat namespace FilterEverything\Filter regardless of their folder,
 *     and src/FormFields/Input.php declares 14 classes in one file.
 *  2. PSR-4 prefixes, for new code whose namespace mirrors its folder
 *     (e.g. FilterEverything\Filter\Frontend\Foo -> src/Frontend/Foo.php).
 *
 * The free build ships without the pro/ folder and pro/filters-pro.php is the
 * only place that registers the PRO class map, so commenting out that single
 * include in filter-everything.php (or deleting pro/) is enough to run the
 * plugin as the free version: PRO classes are then simply unknown and every
 * class_exists('FilterEverything\Filter\Pro\…') check stays false.
 *
 * Files that do work at include time (instantiate a class, add hooks, define
 * functions) are NOT autoloaded; filter-everything.php still includes them
 * explicitly and in order.
 *
 * @since 1.9.7
 */
class Autoloader
{
    /** @var array<string,string> FQCN => absolute file path */
    private static $classMap = [];

    /** @var array<string,string[]> namespace prefix (with trailing \) => base dirs */
    private static $prefixes = [];

    /** @var bool */
    private static $registered = false;

    public static function register()
    {
        if ( ! self::$registered ) {
            spl_autoload_register( [ __CLASS__, 'load' ] );
            self::$registered = true;
        }
    }

    /**
     * @param array<string,string> $map     FQCN => path relative to $baseDir
     * @param string               $baseDir directory the paths are relative to
     */
    public static function addClassMap( array $map, $baseDir )
    {
        $baseDir = rtrim( $baseDir, '/\\' ) . '/';
        foreach ( $map as $class => $relative ) {
            self::$classMap[ ltrim( $class, '\\' ) ] = $baseDir . ltrim( $relative, '/' );
        }
    }

    /**
     * @param string $prefix  namespace prefix, e.g. 'FilterEverything\Filter\'
     * @param string $baseDir directory that corresponds to the prefix
     */
    public static function addNamespace( $prefix, $baseDir )
    {
        $prefix = trim( $prefix, '\\' ) . '\\';
        self::$prefixes[ $prefix ][] = rtrim( $baseDir, '/\\' ) . '/';
    }

    /**
     * spl_autoload_register callback.
     */
    public static function load( $class )
    {
        $class = ltrim( $class, '\\' );

        if ( isset( self::$classMap[ $class ] ) ) {
            return self::requireFile( self::$classMap[ $class ] );
        }

        foreach ( self::$prefixes as $prefix => $dirs ) {
            if ( strpos( $class, $prefix ) !== 0 ) {
                continue;
            }
            $relative = str_replace( '\\', '/', substr( $class, strlen( $prefix ) ) ) . '.php';
            foreach ( $dirs as $dir ) {
                if ( self::requireFile( $dir . $relative ) ) {
                    return true;
                }
            }
        }

        return false;
    }

    private static function requireFile( $file )
    {
        if ( is_file( $file ) ) {
            require_once $file;
            return true;
        }
        return false;
    }
}
